spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nijiverse?useSSL=false&serverTimezone=UTC
    username: root
    password: hiram
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
