spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: my-group-id
      auto-offset-reset: earliest
      producer:
        retries: 0
  datasource:
    url: jdbc:mysql://localhost:3306/nijiverse
    username: root
    password: hiram
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
    server:
      port: 8081
